services:
  - type: web
    name: cipherstudio-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        scope: build
        value: ${MONGODB_URI}
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000

